import turtle

turtle.speed(5)

turtle.penup()
turtle.goto(-100, 100)
turtle.pendown()
turtle.goto(-100, -100)
turtle.goto(100, -100)
turtle.goto(100, 100)
turtle.goto(-100, 100)
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -150)
turtle.pendown()
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -50)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(50)
turtle.pencolor("black")
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.goto(-100, 100)

turtle.penup()
turtle.begin_fill()
turtle.goto(0, 0)
turtle.pendown()
turtle.fillcolor("green")
turtle.goto(-100, -100)
turtle.end_fill()

turtle.penup()
turtle.begin_fill()
turtle.goto(0, 0)
turtle.pendown()
turtle.fillcolor("orange")
turtle.goto(100, 100)
turtle.goto(0, 0)
turtle.goto(100, -100)
turtle.goto(100, 100)
turtle.end_fill()

turtle.done()
