INPUT_MONEY = int(input("Enter how much money to be withdrawn: "))

HUNDERED_BANKNOTE = INPUT_MONEY // 100

INPUT_MONEY -= HUNDERED_BANKNOTE * 100

FIFTY_BANKNOTE = INPUT_MONEY // 50

INPUT_MONEY -= FIFTY_BANKNOTE * 50

TWENTY_BANKNOTE = INPUT_MONEY // 20

INPUT_MONEY -= TWENTY_BANKNOTE * 20

TEN_BANKNOTE = INPUT_MONEY // 10

INPUT_MONEY -= TEN_BANKNOTE * 10

ONE_BANKNOTE = INPUT_MONEY // 1

print("100s:\t", HUNDERED_BANKNOTE, "\n50s:\t", FIFTY_BANKNOTE, "\n20s:\t",
      TWENTY_BANKNOTE, "\n10s:\t", TEN_BANKNOTE, "\n1s:\t", ONE_BANKNOTE)
